### ISSUE TITLE
Latest centos-quarkus-maven image update results in Error: Detected a MBean server in the image heap. 

### ISSUE THREAD

**Issue by gas-stocktrader** [quarkusio/quarkus-images#129]
After update to the centos-quarkus-maven:20.2.0-java11 on 27 January, application no longer builds with the following messages:
Same application was building and working successfully with the previous version of the given image.
Application code is instructed not to use jmx server, which was working previously, clearly indicating some braking change in this version of the image.

Error: Unsupported features in 2 methods
Detailed message:
Error: Detected a MBean server in the image heap. This is currently not supported, but could be changed in the future. Management beans are registered in many global caches that would need to be cleared and properly re-built at image build time. Class of disallowed object: com.sun.jmx.mbeanserver.JmxMBeanServer  To see how this object got instantiated use -H:+TraceClassInitialization. The object was probably created by a class initializer and is reachable from a static field. You can request class initialization at image run time by using the option --initialize-at-run-time=<class-name>. Or you can write your own initialization methods and call them explicitly from your main entry point.
Trace: Object was reached by 
	indexing into array
		constant java.lang.Object[]@1aab8308 reached by 
	reading field java.util.ArrayList.elementData of
		constant java.util.ArrayList@5ae9f4d reached by 
	scanning method javax.management.MBeanServerFactory.addMBeanServer(MBeanServerFactory.java:418)
Call path from entry point to javax.management.MBeanServerFactory.addMBeanServer(MBeanServer): 
	at javax.management.MBeanServerFactory.addMBeanServer(MBeanServerFactory.java:418)
	at javax.management.MBeanServerFactory.createMBeanServer(MBeanServerFactory.java:232)
	at javax.management.MBeanServerFactory.createMBeanServer(MBeanServerFactory.java:192)
	at com.oracle.svm.core.jdk.management.ManagementSupport.getPlatformMBeanServer(ManagementSupport.java:250)
	at com.oracle.svm.core.jdk.management.Target_java_lang_management_ManagementFactory.getPlatformMBeanServer(Target_java_lang_management_ManagementFactory.java:45)
	at org.apache.commons.pool2.impl.BaseGenericObjectPool.jmxUnregister(BaseGenericObjectPool.java:1018)
	at org.apache.commons.pool2.impl.GenericObjectPool.close(GenericObjectPool.java:694)
	at com.oracle.svm.core.posix.NativeSecureRandomFilesCloser$1.close(PosixSunSecuritySubstitutions.java:82)
	at com.oracle.svm.core.posix.NativeSecureRandomFilesCloser$1.run(PosixSunSecuritySubstitutions.java:66)
	at java.lang.Thread.run(Thread.java:834)
	at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:517)
	at com.oracle.svm.core.posix.thread.PosixJavaThreads.pthreadStartRoutine(PosixJavaThreads.java:192)
	at com.oracle.svm.core.code.IsolateEnterStub.PosixJavaThreads_pthreadStartRoutine_e1f4a8c0039f8337338252cd8734f63a79b5e3df(generated:0)
Error: type is not available in this platform: org.graalvm.compiler.hotspot.management.AggregatedMemoryPoolBean
Trace: Object was reached by 
	reading field java.lang.ref.Reference.referent of
		constant java.util.WeakHashMap$Entry@7417cc7d reached by 
	indexing into array
		constant java.util.WeakHashMap$Entry[]@74ea1cf8 reached by 
	reading field java.util.WeakHashMap.table of
		constant com.sun.jmx.mbeanserver.MBeanIntrospector$MBeanInfoMap@6c909167 reached by 
	scanning method com.sun.jmx.mbeanserver.MXBeanIntrospector.getMBeanInfoMap(MXBeanIntrospector.java:68)
Call path from entry point to com.sun.jmx.mbeanserver.MXBeanIntrospector.getMBeanInfoMap(): 
	at com.sun.jmx.mbeanserver.MXBeanIntrospector.getMBeanInfoMap(MXBeanIntrospector.java:68)
	at com.sun.jmx.mbeanserver.MBeanIntrospector.getClassMBeanInfo(MBeanIntrospector.java:416)
	at com.sun.jmx.mbeanserver.MBeanIntrospector.getMBeanInfo(MBeanIntrospector.java:392)
	at com.sun.jmx.mbeanserver.MBeanSupport.<init>(MBeanSupport.java:139)
	at com.sun.jmx.mbeanserver.MXBeanSupport.<init>(MXBeanSupport.java:66)
	at com.sun.jmx.mbeanserver.Introspector.makeDynamicMBean(Introspector.java:203)
	at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.registerObject(DefaultMBeanServerInterceptor.java:888)
	at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.registerMBean(DefaultMBeanServerInterceptor.java:320)
	at com.sun.jmx.mbeanserver.JmxMBeanServer$2.run(JmxMBeanServer.java:1225)
	at com.oracle.svm.core.jdk.Target_java_security_AccessController.doPrivileged(SecuritySubstitutions.java:119)
	at java.net.Socket.getOutputStream(Socket.java:969)
	at org.jboss.logmanager.handlers.TcpOutputStream.flush(TcpOutputStream.java:214)
	at java.io.PrintStream.flush(PrintStream.java:417)
	at com.oracle.svm.jni.functions.JNIFunctions.ExceptionDescribe(JNIFunctions.java:772)
	at com.oracle.svm.core.code.IsolateEnterStub.JNIFunctions_ExceptionDescribe_b5412f7570bccae90b000bc37855f00408b2ad73(generated:0)

com.oracle.svm.core.util.UserError$UserException: Unsupported features in 2 methods
Detailed message:
Error: Detected a MBean server in the image heap. This is currently not supported, but could be changed in the future. Management beans are registered in many global caches that would need to be cleared and properly re-built at image build time. Class of disallowed object: com.sun.jmx.mbeanserver.JmxMBeanServer  To see how this object got instantiated use -H:+TraceClassInitialization. The object was probably created by a class initializer and is reachable from a static field. You can request class initialization at image run time by using the option --initialize-at-run-time=<class-name>. Or you can write your own initialization methods and call them explicitly from your main entry point.
Trace: Object was reached by 
	indexing into array
		constant java.lang.Object[]@1aab8308 reached by 
	reading field java.util.ArrayList.elementData of
		constant java.util.ArrayList@5ae9f4d reached by 
	scanning method javax.management.MBeanServerFactory.addMBeanServer(MBeanServerFactory.java:418)
Call path from entry point to javax.management.MBeanServerFactory.addMBeanServer(MBeanServer): 
	at javax.management.MBeanServerFactory.addMBeanServer(MBeanServerFactory.java:418)
	at javax.management.MBeanServerFactory.createMBeanServer(MBeanServerFactory.java:232)
	at javax.management.MBeanServerFactory.createMBeanServer(MBeanServerFactory.java:192)
	at com.oracle.svm.core.jdk.management.ManagementSupport.getPlatformMBeanServer(ManagementSupport.java:250)
	at com.oracle.svm.core.jdk.management.Target_java_lang_management_ManagementFactory.getPlatformMBeanServer(Target_java_lang_management_ManagementFactory.java:45)
	at org.apache.commons.pool2.impl.BaseGenericObjectPool.jmxUnregister(BaseGenericObjectPool.java:1018)
	at org.apache.commons.pool2.impl.GenericObjectPool.close(GenericObjectPool.java:694)
	at com.oracle.svm.core.posix.NativeSecureRandomFilesCloser$1.close(PosixSunSecuritySubstitutions.java:82)
	at com.oracle.svm.core.posix.NativeSecureRandomFilesCloser$1.run(PosixSunSecuritySubstitutions.java:66)
	at java.lang.Thread.run(Thread.java:834)
	at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:517)
	at com.oracle.svm.core.posix.thread.PosixJavaThreads.pthreadStartRoutine(PosixJavaThreads.java:192)
	at com.oracle.svm.core.code.IsolateEnterStub.PosixJavaThreads_pthreadStartRoutine_e1f4a8c0039f8337338252cd8734f63a79b5e3df(generated:0)
Error: type is not available in this platform: org.graalvm.compiler.hotspot.management.AggregatedMemoryPoolBean
Trace: Object was reached by 
	reading field java.lang.ref.Reference.referent of
		constant java.util.WeakHashMap$Entry@7417cc7d reached by 
	indexing into array
		constant java.util.WeakHashMap$Entry[]@74ea1cf8 reached by 
	reading field java.util.WeakHashMap.table of
		constant com.sun.jmx.mbeanserver.MBeanIntrospector$MBeanInfoMap@6c909167 reached by 
	scanning method com.sun.jmx.mbeanserver.MXBeanIntrospector.getMBeanInfoMap(MXBeanIntrospector.java:68)
Call path from entry point to com.sun.jmx.mbeanserver.MXBeanIntrospector.getMBeanInfoMap(): 
	at com.sun.jmx.mbeanserver.MXBeanIntrospector.getMBeanInfoMap(MXBeanIntrospector.java:68)
	at com.sun.jmx.mbeanserver.MBeanIntrospector.getClassMBeanInfo(MBeanIntrospector.java:416)
	at com.sun.jmx.mbeanserver.MBeanIntrospector.getMBeanInfo(MBeanIntrospector.java:392)
	at com.sun.jmx.mbeanserver.MBeanSupport.<init>(MBeanSupport.java:139)
	at com.sun.jmx.mbeanserver.MXBeanSupport.<init>(MXBeanSupport.java:66)
	at com.sun.jmx.mbeanserver.Introspector.makeDynamicMBean(Introspector.java:203)
	at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.registerObject(DefaultMBeanServerInterceptor.java:888)
	at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.registerMBean(DefaultMBeanServerInterceptor.java:320)
	at com.sun.jmx.mbeanserver.JmxMBeanServer$2.run(JmxMBeanServer.java:1225)
	at com.oracle.svm.core.jdk.Target_java_security_AccessController.doPrivileged(SecuritySubstitutions.java:119)
	at java.net.Socket.getOutputStream(Socket.java:969)
	at org.jboss.logmanager.handlers.TcpOutputStream.flush(TcpOutputStream.java:214)
	at java.io.PrintStream.flush(PrintStream.java:417)
	at com.oracle.svm.jni.functions.JNIFunctions.ExceptionDescribe(JNIFunctions.java:772)
	at com.oracle.svm.core.code.IsolateEnterStub.JNIFunctions_ExceptionDescribe_b5412f7570bccae90b000bc37855f00408b2ad73(generated:0)

	at com.oracle.svm.core.util.UserError.abort(UserError.java:79)
	at com.oracle.svm.hosted.FallbackFeature.reportAsFallback(FallbackFeature.java:217)
	at com.oracle.svm.hosted.NativeImageGenerator.runPointsToAnalysis(NativeImageGenerator.java:765)
	at com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:555)
	at com.oracle.svm.hosted.NativeImageGenerator.lambda$run$0(NativeImageGenerator.java:468)
	at java.base/java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1407)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
Caused by: com.oracle.graal.pointsto.constraints.UnsupportedFeatureException: Unsupported features in 2 methods
Detailed message:
Error: Detected a MBean server in the image heap. This is currently not supported, but could be changed in the future. Management beans are registered in many global caches that would need to be cleared and properly re-built at image build time. Class of disallowed object: com.sun.jmx.mbeanserver.JmxMBeanServer  To see how this object got instantiated use -H:+TraceClassInitialization. The object was probably created by a class initializer and is reachable from a static field. You can request class initialization at image run time by using the option --initialize-at-run-time=<class-name>. Or you can write your own initialization methods and call them explicitly from your main entry point.
Trace: Object was reached by 
	indexing into array
		constant java.lang.Object[]@1aab8308 reached by 
	reading field java.util.ArrayList.elementData of
		constant java.util.ArrayList@5ae9f4d reached by 
	scanning method javax.management.MBeanServerFactory.addMBeanServer(MBeanServerFactory.java:418)
Call path from entry point to javax.management.MBeanServerFactory.addMBeanServer(MBeanServer): 
	at javax.management.MBeanServerFactory.addMBeanServer(MBeanServerFactory.java:418)
	at javax.management.MBeanServerFactory.createMBeanServer(MBeanServerFactory.java:232)
	at javax.management.MBeanServerFactory.createMBeanServer(MBeanServerFactory.java:192)
	at com.oracle.svm.core.jdk.management.ManagementSupport.getPlatformMBeanServer(ManagementSupport.java:250)
	at com.oracle.svm.core.jdk.management.Target_java_lang_management_ManagementFactory.getPlatformMBeanServer(Target_java_lang_management_ManagementFactory.java:45)
	at org.apache.commons.pool2.impl.BaseGenericObjectPool.jmxUnregister(BaseGenericObjectPool.java:1018)
	at org.apache.commons.pool2.impl.GenericObjectPool.close(GenericObjectPool.java:694)
	at com.oracle.svm.core.posix.NativeSecureRandomFilesCloser$1.close(PosixSunSecuritySubstitutions.java:82)
	at com.oracle.svm.core.posix.NativeSecureRandomFilesCloser$1.run(PosixSunSecuritySubstitutions.java:66)
	at java.lang.Thread.run(Thread.java:834)
	at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:517)
	at com.oracle.svm.core.posix.thread.PosixJavaThreads.pthreadStartRoutine(PosixJavaThreads.java:192)
	at com.oracle.svm.core.code.IsolateEnterStub.PosixJavaThreads_pthreadStartRoutine_e1f4a8c0039f8337338252cd8734f63a79b5e3df(generated:0)
Error: type is not available in this platform: org.graalvm.compiler.hotspot.management.AggregatedMemoryPoolBean
Trace: Object was reached by 
	reading field java.lang.ref.Reference.referent of
		constant java.util.WeakHashMap$Entry@7417cc7d reached by 
	indexing into array
		constant java.util.WeakHashMap$Entry[]@74ea1cf8 reached by 
	reading field java.util.WeakHashMap.table of
		constant com.sun.jmx.mbeanserver.MBeanIntrospector$MBeanInfoMap@6c909167 reached by 
	scanning method com.sun.jmx.mbeanserver.MXBeanIntrospector.getMBeanInfoMap(MXBeanIntrospector.java:68)
Call path from entry point to com.sun.jmx.mbeanserver.MXBeanIntrospector.getMBeanInfoMap(): 
	at com.sun.jmx.mbeanserver.MXBeanIntrospector.getMBeanInfoMap(MXBeanIntrospector.java:68)
	at com.sun.jmx.mbeanserver.MBeanIntrospector.getClassMBeanInfo(MBeanIntrospector.java:416)
	at com.sun.jmx.mbeanserver.MBeanIntrospector.getMBeanInfo(MBeanIntrospector.java:392)
	at com.sun.jmx.mbeanserver.MBeanSupport.<init>(MBeanSupport.java:139)
	at com.sun.jmx.mbeanserver.MXBeanSupport.<init>(MXBeanSupport.java:66)
	at com.sun.jmx.mbeanserver.Introspector.makeDynamicMBean(Introspector.java:203)
	at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.registerObject(DefaultMBeanServerInterceptor.java:888)
	at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.registerMBean(DefaultMBeanServerInterceptor.java:320)
	at com.sun.jmx.mbeanserver.JmxMBeanServer$2.run(JmxMBeanServer.java:1225)
	at com.oracle.svm.core.jdk.Target_java_security_AccessController.doPrivileged(SecuritySubstitutions.java:119)
	at java.net.Socket.getOutputStream(Socket.java:969)
	at org.jboss.logmanager.handlers.TcpOutputStream.flush(TcpOutputStream.java:214)
	at java.io.PrintStream.flush(PrintStream.java:417)
	at com.oracle.svm.jni.functions.JNIFunctions.ExceptionDescribe(JNIFunctions.java:772)
	at com.oracle.svm.core.code.IsolateEnterStub.JNIFunctions_ExceptionDescribe_b5412f7570bccae90b000bc37855f00408b2ad73(generated:0)

	at com.oracle.graal.pointsto.constraints.UnsupportedFeatures.report(UnsupportedFeatures.java:129)
	at com.oracle.svm.hosted.NativeImageGenerator.runPointsToAnalysis(NativeImageGenerator.java:762)
	... 8 more
Error: Image build request failed with exit status 1
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------

**Comment by gas-stocktrader** [comment]
Configuration is set via:
```
				//### Quarkus - disable jmx in jedis
				JedisPoolConfig jedisConfiguration = new JedisPoolConfig();
				jedisConfiguration.setJmxEnabled(false);
				logger.info("Initializing JedisPool");
				jedisPool = new JedisPool(jedisConfiguration, jedisURI);
```

which calls later setting objectName = null;

```
    public BaseGenericObjectPool(final BaseObjectPoolConfig<T> config,
            final String jmxNameBase, final String jmxNamePrefix) {
        if (config.getJmxEnabled()) {
            this.objectName = jmxRegister(config, jmxNameBase, jmxNamePrefix);
        } else {
            this.objectName = null;
        }
```

which is used in the jmxUnregister method from the stack
```
    final void jmxUnregister() {
        if (objectName != null) {
            try {
                ManagementFactory.getPlatformMBeanServer().unregisterMBean(
                        objectName);
            } catch (final MBeanRegistrationException | InstanceNotFoundException e) {
                swallowException(e);
            }
        }
    }
```

But since objectName  IS null the code getPlatformMBeanServer() is unreachable during the execution.

**Comment by cescoffier** [comment]
I believe you would need an extension to disable JMX in jedis (note that Quarkus has a Redis extension already)
That being said, I don't know what changed in GraalVM that cause this issue. @galderz any idea?

**Comment by gas-stocktrader** [comment]
You disable JMX in Jedis client simply by that line:
```
jedisConfiguration.setJmxEnabled(false);
```
and as I wrote, it was working fine till yesterday, when image update was released, so I'm wondering what has changed and what could be a workaround for this.

**Comment by galderz** [comment]
> That being said, I don't know what changed in GraalVM that cause this issue. @galderz any idea?

You'd have to generate image with `-Dquarkus.native.enable-reports` and then comb through the call analysis tree to find out why the path is now part of the universe. If you have a point where this didn't occur, you can compare the call trees.

What were you using before `centos-quarkus-maven:20.2.0-java11`? `centos-quarkus-maven:20.3.0-java11` is a more recent one.

**Comment by gas-stocktrader** [comment]
I was and I still use ame tag - centos-quarkus-maven:20.2.0-java11, this was just change from: 
(these are working ones)

sha256:bc024941b19b9155bd08e0737191a103c1fbe86bda24745c39860a107de75de5
sha256:272806f89c0c6faf09ade6d29e337f4a82b69926c248a4c056fd28cd03a46a4b

to (this one published on 27.01 is not working):
sha256:bb07bf059497802f179895a2acbc86b60a0d99a73c4c7ffc5cf6794f64b2af30

So you should check what was updated between these image releases and how it could affect application build.

I'll check 20.3 but my bet is that images before 27 will work and after will not.

**Comment by gas-stocktrader** [comment]
> I believe you would need an extension to disable JMX in jedis (note that Quarkus has a Redis extension already)

Looks like Quarkus Redis extension still doesn't support ssl (rediss scheme) ...
I'm getting the following exception when using `rediss:`
```
2021-02-01 13:40:08,231 INFO  [com.ibm.hyb.clo.sam.sto.sto.StockQuote] (executor-thread-1) java.util.concurrent.CompletionException: java.io.IOException: An existing connection was forcibly closed by the remote host
        at io.smallrye.mutiny.operators.UniBlockingAwait.await(UniBlockingAwait.java:72)
        at io.smallrye.mutiny.groups.UniAwait.atMost(UniAwait.java:61)
        at io.quarkus.redis.client.runtime.RedisClientImpl.await(RedisClientImpl.java:1026)
        at io.quarkus.redis.client.runtime.RedisClientImpl.get(RedisClientImpl.java:237)
        at io.quarkus.redis.client.RedisClient_761b9a6e5f634178e3291b09c1921f229025da0c_Synthetic_ClientProxy.get(RedisClient_761b9a6e5f634178e3291b09c1921f229025da0c_Synthetic_ClientProxy.zig:1467)
        at com.ibm.hybrid.cloud.sample.stocktrader.stockquote.StockQuote.getStockQuote(StockQuote.java:234)
```

So any updates on the issues in the images? And I tried 20.3 image but with the same result.

**Comment by cescoffier** [comment]
It does support ssl. 
You may need to explicitly enable it in your application.properties:
```
quarkus.ssl.native=true
```

**Comment by gas-stocktrader** [comment]
I've added that property, but it doesn't make any difference. Maybe it expects URL in some strange from. My URL is like this in application.properties ( URL works fine with Jedis client):
```
quarkus.redis.hosts=rediss://:apiKey@host:port
```
It is reading that property, as if I put some non existing host I'm getting `UnknownHostException: No such host is known` instead of `connection was forcibly closed `

**Comment by cescoffier** [comment]
The tooling image is abandoned.
