### ISSUE TITLE
podman4 can't build any code with quarkus builder

### ISSUE THREAD

**Issue by zzguang520520** [quarkusio/quarkus-images#226]
podman info
```
[root@~]# podman version
Client:       Podman Engine
Version:      4.3.1
API Version:  4.3.1
Go Version:   go1.18.7
Built:        Fri Nov 11 10:24:13 2022
OS/Arch:      linux/amd64
```
build command incloud builder:
```
mvn -ntp -f /root/alarm-service/pom.xml -DskipTests clean package -Pnative -Dquarkus.container-image.build=false -Dquarkus.native.container-runtime=podman -Dquarkus.container-image.tag=v1.0.0_20230131 -Dquarkus.native.builder-image=quay.io/quarkus/ubi-quarkus-mandrel-builder-image:22.3-java11
mvn -ntp -f /root/alarm-service/pom.xml -DskipTests clean package -Pnative -Dquarkus.container-image.build=false -Dquarkus.native.container-runtime=podman -Dquarkus.container-image.tag=v1.0.0_20230131 -Dquarkus.native.builder-image=quay.io/quarkus/ubi-quarkus-graalvmce-builder-image:22.3-java11
mvn -ntp -f /root/alarm-service/pom.xml -DskipTests clean package -Pnative -Dquarkus.container-image.build=false -Dquarkus.native.container-runtime=podman -Dquarkus.container-image.tag=v1.0.0_20230131 -Dquarkus.native.builder-image=quay.io/quarkus/ubi-quarkus-graalvmce-builder-image:22.1-java11
mvn -ntp -f /root/alarm-service/pom.xml -DskipTests clean package -Pnative -Dquarkus.container-image.build=false -Dquarkus.native.container-runtime=podman -Dquarkus.container-image.tag=v1.0.0_20230131 -Dquarkus.native.builder-image=quay.io/quarkus/ubi-quarkus-mandrel-builder-image:22.1-java11
```

error info:
```
[ERROR] [io.quarkus.deployment.pkg.steps.NativeImageBuildStep] Unable to get GraalVM version from the native-image binary.
[INFO] [io.quarkus.deployment.pkg.steps.NativeImageBuildRunner] podman run --env LANG=C --rm --user 0:0 --userns=keep-id -v /root/alarm-service/target/alarm-service-1.0-SNAPSHOT-native-image-source-jar:/project:z --name build-native-PTYgJ quay.io/quarkus/ubi-quarkus-mandrel-builder-image:22.1-java11 -J-DCoordinatorEnvironmentBean.transactionStatusManagerEnable=false -J-Dsun.nio.ch.maxUpdateArraySize=100 -J-Djava.util.logging.manager=org.jboss.logmanager.LogManager -J-Dlogging.initial-configurator.min-level=500 -J-Dio.netty.leakDetection.level=DISABLED -J-Dio.netty.allocator.maxOrder=3 -J-Dvertx.logger-delegate-factory-class-name=io.quarkus.vertx.core.runtime.VertxLogDelegateFactory -J-Dvertx.disableDnsResolver=true -J-Duser.language=en -J-Duser.country=US -J-Dfile.encoding=UTF-8 --features=io.quarkus.runner.Feature,io.quarkus.jdbc.postgresql.runtime.graal.SQLXMLFeature,io.quarkus.runtime.graal.ResourcesFeature,io.quarkus.runtime.graal.DisableLoggingFeature -H:-ParseOnce -J--add-exports=java.security.jgss/sun.security.krb5=ALL-UNNAMED -J--add-opens=java.base/java.text=ALL-UNNAMED -J--add-opens=java.base/java.io=ALL-UNNAMED -J--add-opens=java.base/java.lang.invoke=ALL-UNNAMED -J--add-opens=java.base/java.util=ALL-UNNAMED -H:ResourceConfigurationFiles=resources-config.json -H:ReflectionConfigurationFiles=reflection-config.json -H:+AllowFoldMethods -J-Djava.awt.headless=true --no-fallback --link-at-build-time -H:+ReportExceptionStackTraces -H:-AddAllCharsets --enable-url-protocols=http,https -H:-UseServiceLoaderFeature -H:+StackTrace -J--add-exports=org.graalvm.sdk/org.graalvm.nativeimage.impl=ALL-UNNAMED -J--add-exports=org.graalvm.nativeimage.builder/com.oracle.svm.core.jdk=ALL-UNNAMED -J--add-exports=org.graalvm.nativeimage.builder/com.oracle.svm.core.configure=ALL-UNNAMED -J--add-exports=org.graalvm.nativeimage.builder/com.oracle.svm.core.jdk.localization=ALL-UNNAMED --exclude-config io\.netty\.netty-codec /META-INF/native-image/io\.netty/netty-codec/generated/handlers/reflect-config\.json --exclude-config io\.netty\.netty-handler /META-INF/native-image/io\.netty/netty-handler/generated/handlers/reflect-config\.json alarm-service-1.0-SNAPSHOT-runner -jar alarm-service-1.0-SNAPSHOT-runner.jar
Error: keep-id is only supported in rootless mode
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  29.799 s
[INFO] Finished at: 2023-01-31T22:15:09-05:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal io.quarkus:quarkus-maven-plugin:2.16.0.Final:build (default) on project alarm-service: Failed to build quarkus application: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
[ERROR] 	[error]: Build step io.quarkus.deployment.pkg.steps.NativeImageBuildStep#build threw an exception: io.quarkus.deployment.pkg.steps.NativeImageBuildStep$ImageGenerationFailureException: Image generation failed. Exit code: 125
[ERROR] 	at io.quarkus.deployment.pkg.steps.NativeImageBuildStep.imageGenerationFailed(NativeImageBuildStep.java:421)
[ERROR] 	at io.quarkus.deployment.pkg.steps.NativeImageBuildStep.build(NativeImageBuildStep.java:262)
[ERROR] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[ERROR] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[ERROR] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[ERROR] 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[ERROR] 	at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:909)
[ERROR] 	at io.quarkus.builder.BuildContext.run(BuildContext.java:281)
[ERROR] 	at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
[ERROR] 	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
[ERROR] 	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
[ERROR] 	at java.base/java.lang.Thread.run(Thread.java:834)
[ERROR] 	at org.jboss.threads.JBossThread.run(JBossThread.java:501)
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
```

The weird thing is that I dropped podman4 to podman3 but it worked

**Comment by zakkak** [comment]
Interesting, I can't reproduce on Fedora 37 with the getting started guide. Can you please paste a bit more of the log, preferably starting from `[INFO] [io.quarkus.deployment.pkg.steps.JarResultBuildStep] Building native image source jar`?

**Comment by peter-777** [comment]
In my environment, I had the same problem with Gradle.

podman -v:
`podman version 4.4.1`

build command:
`./gradlew -i build -Dquarkus.package.type=native -Dquarkus.native.container-build=true -Dquarkus.container-image.build=true -Dquarkus.container-image.tag=native`

error log:
```
(Abbreviated)

> Task :quarkusBuild
Caching disabled for task ':quarkusBuild' because:
  Build cache is disabled
Task ':quarkusBuild' is not up-to-date because:
  Value of input property 'quarkusBuildSystemProperties' has changed for task ':quarkusBuild'
file or directory '/workspaces/simple-app-q/src/integrationTest/java', not found
file or directory '/workspaces/simple-app-q/build/classes/java/quarkus-generated-sources/grpc', not found
file or directory '/workspaces/simple-app-q/build/classes/java/quarkus-generated-sources/avdl', not found
file or directory '/workspaces/simple-app-q/build/classes/java/quarkus-generated-sources/avpr', not found
file or directory '/workspaces/simple-app-q/build/classes/java/quarkus-generated-sources/avsc', not found
file or directory '/workspaces/simple-app-q/src/quarkus-generated-sources/java', not found
file or directory '/workspaces/simple-app-q/src/quarkus-test-generated-sources/java', not found
file or directory '/workspaces/simple-app-q/src/integrationTest/resources', not found
file or directory '/workspaces/simple-app-q/src/native-test/resources', not found
file or directory '/workspaces/simple-app-q/src/quarkus-generated-sources/resources', not found
file or directory '/workspaces/simple-app-q/src/quarkus-test-generated-sources/resources', not found
file or directory '/workspaces/simple-app-q/src/test/resources', not found
JBoss Threads version 3.4.3.Final

Building native image source jar: /workspaces/simple-app-q/build/simple-app-q-1.0.0-SNAPSHOT-native-image-source-jar/simple-app-q-1.0.0-SNAPSHOT-runner.jar
Building native image from /workspaces/simple-app-q/build/simple-app-q-1.0.0-SNAPSHOT-native-image-source-jar/simple-app-q-1.0.0-SNAPSHOT-runner.jar
Using podman to run the native image builder
Checking image status quay.io/quarkus/ubi-quarkus-mandrel-builder-image:22.3-java17
Trying to pull quay.io/quarkus/ubi-quarkus-mandrel-builder-image:22.3-java17...
Getting image source signatures
Copying blob sha256:c5f4a7e2fa03761b49d82d93610545e40ac39b29d0675c363549753919e0d4c8
Copying blob sha256:cc8cfffc43311250a54aa1b545bd957e457a2e930e1b4fc0e5b93a737930597e
Copying blob sha256:3550ee360766546a0eaca7c96269646f601a714ad8e63684f8ace09c2bbbfd19
Copying blob sha256:e6fb0554f4075b0e1334395285686e7b091569111ac5bb9bb79be5ac68a6e8d8
Copying blob sha256:5960b3a10983846b6661a8cdc99c111134ec130e9be67a35a2dc21e9787de8be
Copying blob sha256:84df9b4951929fde40b6ed3b6239e893a680badbe62b9ad39ada5f8a848cd197
Copying blob sha256:7953f6df1d7b385850e53e79a75ea9538ed130453322de1869eb1d624702ac5d
Copying blob sha256:7a8e296d4f186ddcaaa35194f2cfc7731f1336ddba9f08c3b8e6670cd1a30a23
Copying blob sha256:09a4062d1274d2a48927fc5221c49b32b65576ec29dfa0352216c947821184e1
Copying blob sha256:5c1b332c5706742a9c74979b6d93ffcd713523b3bccbf1320fb1504157a277a6
Copying blob sha256:030471f4ed808af6ba30a73e39de68cc3f40814c6e5a225daf52ef5a4c462278
Copying blob sha256:40b790be7a61e3356cf11ead3a605881275fa5c5066d5f3f2b4a4204c06c9495
Copying blob sha256:6c31ad5ba21738d4a08543c939430554a7719b9aced1eaee931abda7c532934b
Copying blob sha256:4f4fb700ef54461cfa02571ae0db9a0dc1e0cdb5577484a6d75e68dc38e8acc1
Copying blob sha256:4f4fb700ef54461cfa02571ae0db9a0dc1e0cdb5577484a6d75e68dc38e8acc1
Copying config sha256:4b235d59d8893b1812c9831fd45690d4fa0a404081145437eefaa2faf71a0992
Writing manifest to image destination
Storing signatures
4b235d59d8893b1812c9831fd45690d4fa0a404081145437eefaa2faf71a0992
Unable to get GraalVM version from the native-image binary.
podman run --env LANG=C --rm --user 0:0 --userns=keep-id -v /workspaces/simple-app-q/build/simple-app-q-1.0.0-SNAPSHOT-native-image-source-jar:/project:z --name build-native-pSelv quay.io/quarkus/ubi-quarkus-mandrel-builder-image:22.3-java17 -J-Djava.util.logging.manager=org.jboss.logmanager.LogManager -J-Dsun.nio.ch.maxUpdateArraySize=100 -J-Dlogging.initial-configurator.min-level=500 -J-Dvertx.logger-delegate-factory-class-name=io.quarkus.vertx.core.runtime.VertxLogDelegateFactory -J-Dvertx.disableDnsResolver=true -J-Dio.netty.noUnsafe=true -J-Dio.netty.leakDetection.level=DISABLED -J-Dio.netty.allocator.maxOrder=3 -J-Duser.language=ja -J-Duser.country=JP -J-Dfile.encoding=UTF-8 --features=io.quarkus.runner.Feature,io.quarkus.runtime.graal.ResourcesFeature,io.quarkus.runtime.graal.DisableLoggingFeature -H:-ParseOnce -J--add-exports=java.security.jgss/sun.security.krb5=ALL-UNNAMED -J--add-opens=java.base/java.text=ALL-UNNAMED -J--add-opens=java.base/java.io=ALL-UNNAMED -J--add-opens=java.base/java.lang.invoke=ALL-UNNAMED -J--add-opens=java.base/java.util=ALL-UNNAMED -H:+AllowFoldMethods -J-Djava.awt.headless=true --no-fallback --link-at-build-time -H:+ReportExceptionStackTraces -H:-AddAllCharsets --enable-url-protocols=http -H:-UseServiceLoaderFeature -H:+StackTrace -J--add-exports=org.graalvm.sdk/org.graalvm.nativeimage.impl=ALL-UNNAMED -J--add-exports=org.graalvm.nativeimage.builder/com.oracle.svm.core.jdk=ALL-UNNAMED -J--add-exports=org.graalvm.nativeimage.builder/com.oracle.svm.core.configure=ALL-UNNAMED -J--add-exports=org.graalvm.nativeimage.builder/com.oracle.svm.core.jdk.localization=ALL-UNNAMED --exclude-config io\.netty\.netty-codec /META-INF/native-image/io\.netty/netty-codec/generated/handlers/reflect-config\.json --exclude-config io\.netty\.netty-handler /META-INF/native-image/io\.netty/netty-handler/generated/handlers/reflect-config\.json simple-app-q-1.0.0-SNAPSHOT-runner -jar simple-app-q-1.0.0-SNAPSHOT-runner.jar
Error: keep-id is only supported in rootless mode

> Task :quarkusBuild FAILED
:quarkusBuild (Thread[Execution worker Thread 4,5,main]) completed. Took 1 mins 24.984 secs.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':quarkusBuild'.
> io.quarkus.builder.BuildException: Build failure: Build failed due to errors
        [error]: Build step io.quarkus.deployment.pkg.steps.NativeImageBuildStep#build threw an exception: io.quarkus.deployment.pkg.steps.NativeImageBuildStep$ImageGenerationFailureException: Image generation failed. Exit code: 125
        at io.quarkus.deployment.pkg.steps.NativeImageBuildStep.imageGenerationFailed(NativeImageBuildStep.java:422)
        at io.quarkus.deployment.pkg.steps.NativeImageBuildStep.build(NativeImageBuildStep.java:263)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:909)
        at io.quarkus.builder.BuildContext.run(BuildContext.java:281)
        at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
        at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
        at java.base/java.lang.Thread.run(Thread.java:857)
        at org.jboss.threads.JBossThread.run(JBossThread.java:501)


* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1m 30s
```

@zakkak 
Are you testing with rootless podman by any chance?

**Comment by zakkak** [comment]
> @zakkak Are you testing with rootless podman by any chance?

Correct. I wonder how I missed:

```
Error: keep-id is only supported in rootless mode
```

the first time.

So apparently Quarkus should not pass `--userns=keep-id` when running podman as root (see https://github.com/containers/podman/issues/14515). I am working on a fix for that.
