### ISSUE TITLE
Push Images failed: ubi-quarkus-graalvmce-builder-image:22.3.0-java17-arm64

### ISSUE THREAD

**Issue by Karm** [quarkusio/quarkus-images#232]
Looking at `HTTP status: 500 Internal Server Error`, I wonder if it could be just a Quay acting up?
I am re-running the failed GHA job...

```
[INFO] ⚙️	Push the images: [quay.io/quarkus/ubi-quarkus-graalvmce-builder-image:22.3.0-java17-arm64, quay.io/quarkus/ubi-quarkus-graalvmce-builder-image:22.3.0-java17-amd64]
[INFO] ⚙️	Pushing quay.io/quarkus/ubi-quarkus-graalvmce-builder-image:22.3.0-java17-arm64 (arm64)
[INFO] 🐋	The push refers to repository [quay.io/quarkus/ubi-quarkus-graalvmce-builder-image]
[INFO] 🐋	5f70bf18a086: Preparing
[INFO] 🐋	5f70bf18a086: Preparing
[INFO] 🐋	7fff3f1040ba: Preparing
[INFO] 🐋	d29562898da0: Preparing
[INFO] 🐋	3e97e3f8577d: Preparing
[INFO] 🐋	965cbe01aee0: Preparing
[INFO] 🐋	b9896e883cf5: Preparing
[INFO] 🐋	16ef40261be6: Preparing
[INFO] 🐋	9d903ce13588: Preparing
[INFO] 🐋	9530b5824ed2: Preparing
[INFO] 🐋	7db21607e9f6: Preparing
[INFO] 🐋	53ee2874209a: Preparing
[INFO] 🐋	5504812f9d55: Preparing
[INFO] 🐋	5e077cb01e78: Preparing
[INFO] 🐋	293c2bf88d54: Preparing
[INFO] 🐋	b9896e883cf5: Waiting
[INFO] 🐋	16ef40261be6: Waiting
[INFO] 🐋	9d903ce13588: Waiting
[INFO] 🐋	9530b5824ed2: Waiting
[INFO] 🐋	7db21607e9f6: Waiting
[INFO] 🐋	53ee2874209a: Waiting
[INFO] 🐋	5504812f9d55: Waiting
[INFO] 🐋	5e077cb01e78: Waiting
[INFO] 🐋	293c2bf88d54: Waiting
[INFO] 🐋	5f70bf18a086: Layer already exists
[INFO] 🐋	965cbe01aee0: Layer already exists
[INFO] 🐋	b9896e883cf5: Layer already exists
[INFO] 🐋	16ef40261be6: Layer already exists
[INFO] 🐋	9d903ce13588: Layer already exists
[INFO] 🐋	9530b5824ed2: Layer already exists
[INFO] 🐋	53ee2874209a: Layer already exists
[INFO] 🐋	7db21607e9f6: Layer already exists
[INFO] 🐋	5e077cb01e78: Layer already exists
[INFO] 🐋	5504812f9d55: Layer already exists
[INFO] 🐋	293c2bf88d54: Layer already exists
[INFO] 🐋	7fff3f1040ba: Pushed
[INFO] 🐋	3e97e3f8577d: Pushed
[INFO] 🐋	d29562898da0: Pushed
[INFO] 🐋	received unexpected HTTP status: 500 Internal Server Error
[INFO] java.lang.RuntimeException: Unable to push quay.io/quarkus/ubi-quarkus-graalvmce-builder-image:22.3.0-java17-arm64
[INFO] 	at io.quarkus.images.MultiArchImage.lambda$buildAndPush$1(MultiArchImage.java:73)
[INFO] 	at io.quarkus.images.utils.Exec.execute(Exec.java:27)
[INFO] 	at io.quarkus.images.MultiArchImage.buildAndPush(MultiArchImage.java:72)
[INFO] 	at io.quarkus.images.Push.call(Push.java:63)
[INFO] 	at io.quarkus.images.Push.call(Push.java:19)
[INFO] 	at picocli.CommandLine.executeUserObject(CommandLine.java:1953)
[INFO] 	at picocli.CommandLine.access$1300(CommandLine.java:145)
[INFO] 	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2358)
[INFO] 	at picocli.CommandLine$RunLast.handle(CommandLine.java:2352)
[INFO] 	at picocli.CommandLine$RunLast.handle(CommandLine.java:2314)
[INFO] 	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
[INFO] 	at picocli.CommandLine$RunLast.execute(CommandLine.java:2316)
[INFO] 	at picocli.CommandLine.execute(CommandLine.java:2078)
[INFO] 	at io.quarkus.images.Push.main(Push.java:71)
[INFO] Caused by: org.zeroturnaround.exec.InvalidExitValueException: Unexpected exit value: 1, allowed exit values: [0], executed command [docker, push, quay.io/quarkus/ubi-quarkus-graalvmce-builder-image:22.3.0-java17-arm64]
```

**Comment by Karm** [comment]
Re-run was successful.
