### ISSUE TITLE
Unsupported Encoding Exception JIS_X_0212

### ISSUE THREAD

**Issue by evgeniysharapov** [quarkusio/quarkus-images#84]
I am trying to build native executable for a simple java application with quay.io/quarkus/ubi-quarkus-native-image:20.1.0-java11
What I get is an error

```
Fatal error:com.oracle.graal.pointsto.util.AnalysisError$ParsingError: Error encountered while parsing sun.nio.cs.JIS_X_0212.newEncoder()
Parsing context:
        parsing java.lang.StringCoding.encode(StringCoding.java:444)
        parsing java.lang.String.getBytes(String.java:964)

< a lot of stacktrace >
Caused by: com.oracle.svm.core.util.VMError$HostedError: Could not find non-initialized charset JIS_X_0212.java                                                                                                          at com.oracle.svm.core.util.VMError.shouldNotReachHere(VMError.java:76)
        at com.oracle.svm.core.jdk.LocalizationFeature$CharsetNodePlugin.handleInvoke(LocalizationFeature.java:125)
        at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.tryNodePluginForInvocation(BytecodeParser.java:2216)
        at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.appendInvoke(BytecodeParser.java:1904)
        at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.genInvokeStatic(BytecodeParser.java:1682)
        at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.genInvokeStatic(BytecodeParser.java:1662)
        at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.processBytecode(BytecodeParser.java:5340)                                                                                                   at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.iterateBytecodesForBlock(BytecodeParser.java:3423)
        ... 24 more
Caused by: java.nio.charset.UnsupportedCharsetException: JIS_X_0212
        at java.base/java.nio.charset.Charset.forName(Charset.java:529)
        at com.oracle.svm.core.jdk.LocalizationFeature$CharsetNodePlugin.handleInvoke(LocalizationFeature.java:122)
        ... 30 more
```

What could be done to alleviate it ? This seems like it could be something other people stumbled upon. My application has nothing to do with charsets or Japanese.

**Comment by galderz** [comment]
The builder image seems to have a limiting default encoding (see https://github.com/quarkusio/quarkus-images/issues/86), so I don't know if you're impacted by that. There's a PR with a change that would fix things.

To be able to help further it'd be useful to have a reproducer or at least some info on what in your application could be triggering this.

**Comment by cescoffier** [comment]
Closing as we have now the "encoding" module
